#ifndef    _NVIC_CONFIG_H_
#define    _NVIC_CONFIG_H_

/*
    NVIC_4BITS_GROUP_0BITS_SUB 	 
    NVIC_3BITS_GROUP_1BITS_SUB   
    NVIC_2BITS_GROUP_2BITS_SUB   
    NVIC_1BITS_GROUP_3BITS_SUB   	
    NVIC_0BITS_GROUP_4BITS_SUB   
*/


#define 	NO_GROUPS_NO_SUB		NVIC_2BITS_GROUP_2BITS_SUB
#endif 
